In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [5]:
## Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
## Preprocess the data
## Drop irrelevant columns
data = data.drop(["RowNumber","CustomerId", "Surname"], axis=1)

In [7]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [ ]:
## Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [90]:
label_encoder_gender

LabelEncoder()

In [108]:
print(data.columns)

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited',
       'Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype='str')

In [109]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

onehot_encoder_geo = OneHotEncoder(sparse_output=False)

geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography_France', 'Geography_Germany', 'Geography_Spain']])

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography_France', 'Geography_Germany', 'Geography_Spain'])
)

In [101]:
## Onehot encode 'Geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

KeyError: "None of [Index(['Geography'], dtype='str')] are in the [columns]"

In [100]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [17]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [106]:
## save the encoder and scaler
with open('label_encoder_gender.pk1', 'wb') as file:
  pickle.dump(label_encoder_gender, file)
with open('onehot_encoder_geo.pk1', 'wb') as file:
  pickle.dump(onehot_encoder_geo, file)

In [51]:
## Divid the dataset into dependednt and independent features
X = data.drop('Exited', axis=1)
Y = data['Exited']

## Split the data in taining and testing sets
X_train, X_test, Y_tain, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

## Scale these features
scaler = StandardScaler()
X_train['Gender'] = X_train['Gender'].map({'Male': 1, 'Female': 0})
X_test['Gender'] = X_test['Gender'].map({'Male': 1, 'Female': 0})
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
X_test

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
6252          596    Male  ...                1.0              0.0
4684          623    Male  ...                0.0              0.0
1731          601  Female  ...                0.0              1.0
4742          506    Male  ...                1.0              0.0
4521          560  Female  ...                0.0              1.0
...           ...     ...  ...                ...              ...
6412          602  Female  ...                1.0              0.0
8285          609    Male  ...                0.0              0.0
7853          730  Female  ...                0.0              0.0
1095          692    Male  ...                0.0              0.0
6929          628    Male  ...                1.0              0.0

[2000 rows x 12 columns]

In [110]:
print(Y_tain.dtypes)
print(X_train.dtype)

int64
float64

In [48]:
X_train['Gender'] = X_train['Gender'].map({'Male': 1, 'Female': 0})
X_test['Gender'] = X_test['Gender'].map({'Male': 1, 'Female': 0})
print(X_train.dtypes)

CreditScore            int64
Gender               float64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Geography_France     float64
Geography_Germany    float64
Geography_Spain      float64
dtype: object

In [17]:
with open('scaler.pk1', 'wb') as file:
  pickle.dump(scaler, file)

In [23]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619  Female  ...                0.0              0.0
1             608  Female  ...                0.0              1.0
2             502  Female  ...                0.0              0.0
3             699  Female  ...                0.0              0.0
4             850  Female  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771    Male  ...                0.0              0.0
9996          516    Male  ...                0.0              0.0
9997          709  Female  ...                0.0              0.0
9998          772    Male  ...                1.0              0.0
9999          792  Female  ...                0.0              0.0

[10000 rows x 13 columns]

### ANN Implementation

In [1]:
import tensorflow as ts
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
from tensorflow.keras.layers import Dense

In [24]:
X_train.shape[1]

12

In [25]:
## Build Oir ANN Model
model = Sequential([
  Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
  Dense(32, activation='relu'),
  Dense(1, activation='sigmoid')
])

/home/ekele/Documents/study/AI Engineering/ANN Classification/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1778578231.590276   10877 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [67]:
## Compile the model
# model.compile(optimizer = opt, loss='binary_crossentropy', metrics=['accuracy'])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [82]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import os

log_dir = "logs/fit"
os.makedirs(log_dir, exist_ok=True)

tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

# log_dir =  'log/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [71]:
## Set up Early stopping
early_stopping_callback =  EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [59]:
print(X_train.shape)
print(Y_tain.shape)

(8000, 12)
(8000,)

In [60]:
Y_train = Y_tain

In [83]:
## Train the model
history = model.fit(
  X_train, Y_train, 
  validation_data=(X_test, Y_test), 
  epochs = 100,
  callbacks = [tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8658 - loss: 0.3158 - val_accuracy: 0.8660 - val_loss: 0.3365
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8699 - loss: 0.3138 - val_accuracy: 0.8665 - val_loss: 0.3437
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8698 - loss: 0.3133 - val_accuracy: 0.8595 - val_loss: 0.3423
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8685 - loss: 0.3109 - val_accuracy: 0.8615 - val_loss: 0.3378
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8708 - loss: 0.3111 - val_accuracy: 0.8645 - val_loss: 0.3395
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8702 - loss: 0.3092 - val_accuracy: 0.8615 - val_loss: 0.3436
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8711 - loss: 0.3089 - val_accuracy: 0.8605 - val_loss: 0.3430
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8705 - loss: 0.3082 - val_accuracy: 0.8620 - val_loss: 0.3429
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8716 - loss: 0.3066 - val_accuracy: 0.8650 - val_loss: 0.3414
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8735 - loss: 0.3051 - val_accuracy: 0.8600 - val_loss: 0.3424

In [73]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [111]:
## Load Tensorboard Extension
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 19849), started 4:13:44 ago. (Use '!kill 19849' to kill it.)